### ISSUE TITLE
longtable caption differs to table caption

### ISSUE THREAD

**Issue by hydrahamster** [zachscrivena/simple-thesis-dissertation#1]
Hi there,
My thesis has both `table` and `longtable` in it. Now the problem is this: The `longtable` captions are quite different to the tables and figures captions. I've tried to sort it out through `\captionsetup` but can't work out exactly how to match this style. 

Could you please help with this?

Thanks,
Liza
![Tex-table-problems](https://user-images.githubusercontent.com/4579110/60065090-017d3b00-9746-11e9-9e52-554910cd166c.png)

**Comment by zachscrivena** [comment]
Thanks Liza for your feedback! I've added support for longtable in the latest commit. Could you try again to see if it works now?

**Comment by hydrahamster** [comment]
Hi Zach,

Thanks for looking into it! It works, thank you =) And thanks for making this resource available, it's really helped getting my thesis finished.

All the best,
Liza

**Comment by zachscrivena** [comment]
Glad to help 😃 Good luck on the thesis!
